<?php
    # Program: newsfeed.php
    #    Date: 10-Aug-2024
    #  Author: gerry.walterscheid@gmail.com
    # Descrip: Display RSS feed stories from BBC World News every 15 sec.

    session_start();

    header("Content-type: text/xml");
    header("Refresh:15");

    $urlPath = "http://192.168.3.250/cisco/newsfeed.php";

    # Recall prior variable state.
    $id = $_SESSION['id'] ?? "";            # App name.

    # Prevent data corruption from prior application.
    if ($id == "newsfeed") {
        $i = $_SESSION['i'];                # Index pointing to next story.
        $m = $_SESSION['m'];                # Mode to determine view type.
        $update = $_SESSION['update']; }    # Time from prior page update.
    else {
        $i = 0;
        $m = 0;
        $update = 0; }

    # Define list of prohibited words within news stories.
    $words = array( "bodies", "body", "bomb", "crash", "dead", 
                    "death", "die", "drown", "electrocute", "injure", 
                    "kill", "murder", "overdose", "rape", "sex", "shoot", 
                    "shot", "stab", "suffocate", "suicide", "victim" );

    # Update local news content every half hour.
    $filename = "/volume1/web/cisco/bbc.txt";
    $last_update = filemtime($filename);

    if ((time() - $last_update) / 60 > 30) {

        # Get lastest content from RSS Feed.
        $url="http://feeds.bbci.co.uk/news/world/rss.xml#";
        $feeds = simplexml_load_file($url);

        # Save the RSS Feed data locally, to reduce RSS requests.
        $file = fopen($filename, "w");

        # Save only the stories that do not contain prohibited words.
        foreach ($feeds->channel->item as $item) {

            # Remove un-printable characters from description.
            $item->description=preg_replace('/[[:^print:]]/', '', $item->description);

            # Convert story to lowercase.
            $text = strtolower(" $item->title $item->description");

            $found = False;

            # Check if story contains any prohibited words.
            foreach ($words as $word) 
                if (strpos($text, $word)) 
                    $found = True;

                # If story doesn't contain prohibited words, go ahead and save.
                if (!$found) {
                    fwrite($file, "$item->title\n");
                    fwrite($file, "$item->description\n\n"); }
        }

        fclose($file);
    }	

    # Load locally stored RSS Feed content.
    $array = explode("\n", file_get_contents($filename));

    # Get cmd selection from user and implement.
    $cmd = $_GET['key'] ?? 0;

    # Ignore old commands generated by page refresh delay.
    if (time() - $update < 15) 
        switch($cmd) {
        case 1 : # mode
            $m = ($m + 1)%2;
            $i = $i - 3; 
            break;

        case 2 : # prev
            $i = $i - 6;
            if ($i < 0)
                $i = count($array) - 7;
            break;
        }

    # Cleanup news article to avoid extraneous characters in output.
    for ($p = $i; $p < $i + 2; $p++) {

        # Replace special characters with their HTML equivalents..
        $array[$p] = str_replace(" "," ",$array[$p]);	    # non-printable space
        $array[$p] = str_replace("– ","-",$array[$p]);	    # non-printable hyphen
    	$array[$p] = str_replace("’","'",$array[$p]);       # acute accent 
    	$array[$p] = str_replace("‘","'",$array[$p]);       # acute accent 
        $array[$p] = str_replace("&","&amp;",$array[$p]);   # ampersand
        $array[$p] = str_replace("“","&#34;",$array[$p]);   # left double quote
        $array[$p] = str_replace("”","&#34;",$array[$p]);   # right double quote

    	$array[$p] = str_replace("á","&#225;",$array[$p]);  # lowercase a accent
    	$array[$p] = str_replace("é","&#233;",$array[$p]);  # lowercase e accent
    	$array[$p] = str_replace("í","&#237;",$array[$p]);  # lowercase i accent
    	$array[$p] = str_replace("ó","&#243;",$array[$p]);  # lowercase o accent
    	$array[$p] = str_replace("ú","&#250;",$array[$p]);  # lowercase u accent

    	$array[$p] = str_replace("Á","&#193;",$array[$p]);  # uppercase a accent
    	$array[$p] = str_replace("É","&#201;",$array[$p]);  # uppercase e accent
    	$array[$p] = str_replace("Í","&#205;",$array[$p]);  # uppercase i accent
    	$array[$p] = str_replace("Ó","&#201;",$array[$p]);  # uppercase o accent
    	$array[$p] = str_replace("Ú","&#218;",$array[$p]);  # uppercase u accent

        $array[$p] = str_replace("…","...",$array[$p]);     # elipses

        # Remove trailing spaces in sentences.
        $length = strlen($array[$p]) - 1;
        if (substr($array[$p],$length,1) == " ")
            $array[$p] = substr($array[$p],0,$length - 1);

        # Add a period if found to be missing.
    	$length = strlen($array[$p]) - 1;
    	if ((substr($array[$p],$length,1) != "?") && 
    	    (substr($array[$p],$length,1) != "!") &&
    	    (substr($array[$p],$length,1) != "."))
            $array[$p] = substr($array[$p],0,$length + 2).".";
    }	

    echo "<CiscoIPPhoneText>\n";

    # Display story, using the current mode (brief, full).
    switch($m) {
        case 0 : # Display brief view of story.
            echo "  <Title>BBC World Service - Brief</Title>\n";
            echo "  <Text>$array[$i]";
            break;

        case 1 : # Display full view of story.
            $j = $i + 1;
            echo "  <Title>BBC World Service - Detail</Title>\n";
            echo "  <Text>$array[$i] $array[$j]";
            break;
    }

    # Advance index to next story.
    $i += 3;

    # If no story is present, reset back to the beginning.
    if (empty($array[$i])) 
        $i = 0;

    echo "</Text>\n";

    echo "  <SoftKeyItem>\n";
    echo "    <Name>Mode</Name>\n";
    echo "    <URL>$urlPath?key=1</URL>\n";
    echo "    <Position>1</Position>\n";
    echo "  </SoftKeyItem>\n";
            
    echo "  <SoftKeyItem>\n";
    echo "    <Name>Prev</Name>\n";
    echo "    <URL>$urlPath?key=2</URL>\n";
    echo "    <Position>2</Position>\n";
    echo "  </SoftKeyItem>\n";
            
    echo "  <SoftKeyItem>\n";
    echo "    <Name>Next</Name>\n";
    echo "    <URL>$urlPath?key=3</URL>\n";
    echo "    <Position>3</Position>\n";
    echo "  </SoftKeyItem>\n";
            
    echo "  <SoftKeyItem>\n";
    echo "    <Name>Exit</Name>\n";
    echo "    <URL>SoftKey:Exit</URL>\n";
    echo "    <Position>4</Position>\n";
    echo "  </SoftKeyItem>\n";

    echo "  <Prompt>News update every 15 seconds.</Prompt>\n";
    echo "</CiscoIPPhoneText>\n";

    # Save variable states for next session.
    $_SESSION['id'] = "newsfeed";
    $_SESSION['i'] = $i;
    $_SESSION['m'] = $m;
    $_SESSION['update'] = time();
?>
